//
// Created by jadjer on 23.11.2021.
//

#ifndef ICOL_MES_CONTROLLER_INCLUDE_DATALAYER_LOGGER_LOGGERPROXY_HPP_
#define ICOL_MES_CONTROLLER_INCLUDE_DATALAYER_LOGGER_LOGGERPROXY_HPP_

#include <logger/Logger.hpp>

#endif//ICOL_MES_CONTROLLER_INCLUDE_DATALAYER_LOGGER_LOGGERPROXY_HPP_
